
CREATE TABLE TAB_IDENTITY(ID INT AUTO_INCREMENT, 
DESCRITOR VARCHAR(20),PRIMARY KEY(ID));

INSERT INTO TAB_IDENTITY(DESCRITOR) VALUES('CLIENTE1');

SELECT * FROM TAB_IDENTITY;

INSERT INTO TAB_IDENTITY(DESCRITOR) VALUES('CLIENTE2');
INSERT INTO TAB_IDENTITY(DESCRITOR) VALUES('CLIENTE3');
INSERT INTO TAB_IDENTITY(ID, DESCRITOR) VALUES(NULL,'CLIENTE3');
INSERT INTO TAB_IDENTITY(ID, DESCRITOR) VALUES(NULL,'CLIENTE5');
INSERT INTO TAB_IDENTITY(ID, DESCRITOR) VALUES(NULL,'CLIENTE6');

DELETE FROM TAB_IDENTITY WHERE ID = 2;
DELETE FROM TAB_IDENTITY WHERE ID = 5;
