CREATE TABLE CLIENTES(
CPF VARCHAR(11) NOT NULL,
NOME VARCHAR(100) NULL,
ENDERECO VARCHAR(150) NULL,
BAIRRO VARCHAR(50) NULL,
CIDADE VARCHAR(50) NULL,
ESTADO VARCHAR(50) NULL,
CEP VARCHAR(8) NULL,
DATA_DE_NASCIMENTO DATE NULL,
IDADE INT(32),
SEXO VARCHAR(1),
LIMITE_DE_CREDITO FLOAT,
VOLUME_DE_COMPRA FLOAT,
PRIMEIRA_COMPRA BIT(1),
PRIMARY KEY(CPF)

);

SELECT * FROM clientes;

