CREATE TABLE VENDAS(

NUMERO VARCHAR(95) NOT NULL,
DATA_DE_VENDA DATE NULL,
CPF VARCHAR(11) NOT NULL,
MATRICULA VARCHAR(11) NOT NULL,
IMPOSTO FLOAT NULL,
PRIMARY KEY(NUMERO)

);

ALTER TABLE VENDAS ADD CONSTRAINT FK_CLIENTES # CHAVE 
FOREIGN KEY (CPF) REFERENCES CLIENTES(CPF);


ALTER TABLE VENDAS ADD CONSTRAINT FK_VENDEDORES  # CHAVE 
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES(MATRICULA);

ALTER TABLE VENDAS RENAME NOTAS; # MUDANDO O NOME DA TABELA