
CREATE TABLE TAB_PADRAO(
ID INT AUTO_INCREMENT,
DESCRITOR VARCHAR(20),
ENDERECO VARCHAR(100) NULL,
CIDADE VARCHAR(50) DEFAULT 'Rio de Janeiro',
DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
PRIMARY KEY(ID)
);

INSERT INTO TAB_PADRAO
(DESCRITOR, ENDERECO, CIDADE, DATA_CRIACAO)
VALUES
('CLIENTE X', 'Rua das Flores', 'São Paulo','2024-05-05');


SELECT * FROM TAB_PADRAO;