# CONVERSÃO DE DADOS 

SELECT CURRENT_TIMESTAMP() AS RESULTADO;

SELECT CONCAT('O dia de hoje é: ', CURRENT_TIMESTAMP()) AS RESULTADO;

SELECT CONCAT('O dia de hoje é: ', 
DATE_FORMAT (CURRENT_TIMESTAMP(),' %m/%y')) AS RESULTADO;

SELECT CONCAT('O dia de hoje é: ', 
DATE_FORMAT (CURRENT_TIMESTAMP(),'%d/ %c/%y')) AS RESULTADO;