# Funções de string MySQL

SELECT LTRIM('   OLÁ') AS RESULTADO;

SELECT RTRIM('OLÁ   ')AS RESULTADO;

SELECT TRIM(' OLÁ    ')AS RESULTADO;

SELECT CONCAT('OLÁ', ' ', 'TUDO BEM', '?')AS RESULTADO;

SELECT UPPER('olá, tudo bem?')AS RESULTADO;

SELECT SUBSTRING('olá, tudo bem?', 6)AS RESULTADO;

SELECT SUBSTRING('olá, tudo bem?', 6, 4)AS RESULTADO;

SELECT REVERSE('olá, tudo bem?')AS RESULTADO;

SELECT LENGTH('olá, tudo bem?')AS RESULTADO;

SELECT CONCAT(NOME, '(', CPF, ') ') AS RESULTADO FROM tabela_de_clientes;


