#HAVING
# permite filtrar os dados agregados pela instrução GROUP BY para que o usuário 
# obtenha um conjunto limitado de registros para visualização.

SELECT ESTADO, SUM(LIMITE_DE_CREDITO)
AS SOMA_LIMITE FROM tabela_de_clientes GROUP BY ESTADO;


SELECT ESTADO, SUM(LIMITE_DE_CREDITO)
AS SOMA_LIMITE FROM tabela_de_clientes GROUP BY ESTADO
HAVING SUM(LIMITE_DE_CREDITO) > 900000;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO,
MIN(PRECO_DE_LISTA) AS MENOR_PRECO FROM tabela_de_produtos
GROUP BY EMBALAGEM;


SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO,
MIN(PRECO_DE_LISTA) AS MENOR_PRECO FROM tabela_de_produtos
GROUP BY EMBALAGEM HAVING SUM(PRECO_DE_LISTA) <= 80;

