# JOINs
/*
INEER JOIN - ELE RETORNA SOMENTE QUANDO TEMOS CHAVES CORRESPONDENTES
LEFT JOIN - RETORNA TODOS DA TABELA DA ESQUERDA E SOMENTE OS CORRESPONDENTES NA DA DIREITA
RIGHT JOIN - RETORNA TODOS DA TABELA DA DIREITA E SOMENTE OS CORRESPONDENTES NA DA DIREITA
FULL JOIN - RETORNA TODOS OS REGISTROS DE TODAS AS TABELAS
CROSS JOIN - RETORNA O PRODUTO CARTESIANO DAS DUAS TABELAS
*/

SELECT * FROM tabela_de_vendedores;
SELECT * FROM notas_fiscais;

SELECT * FROM tabela_de_vendedores A
INNER JOIN notas_fiscais B
ON A.MATRICULA = B.MATRICULA;