# RIGHT JOIN - RETORNA TODOS DA TABELA DA DIREITA E SOMENTE OS CORRESPONDENTES NA DA DIREITA

SELECT DISTINCT A.CPF, A.NOME, B.CPF FROM notas_fiscais B
RIGHT JOIN tabela_de_clientes A ON A.CPF = B.CPF WHERE B.CPF IS NULL;