# EXERCICIO 11
# CRIE UM BANCO DE DADOS CHAMADO CADASTRO;
# CRIE UMA TABELA CHAMADA PESSOAS;
# COLUNAS NOME, RG, CPF E LIMITE;
#  NOME, RG, CPF E LIMITE SÃO DADOS DE TEXTO;
# LIMITE É UM VALOR NÚMERICO 
# INSIRA 5 DADOS ;