#EXERCICIO 16
# SELECIONE NA TABELA departments TODAS AS COLUNAS,
# PORÉM LIMITE A 5 RESULTADOS E ORDENE DE FORMA ASCENDENTE
# A ORDEM DEVE SER PELA COLUNA DE TITLE

SELECT * FROM titles
ORDER BY title LIMIT 5;
