# EXERCICIO 19
# NA TABELA emmployees FAÇA UM SELECT DE TODOS OS REGISTRO QUE 
# CONTENHAM NO SOBRENOME:
# FACELLO E PEAC;
# UTILIZE O IN

SELECT * FROM employees 
WHERE last_name IN('Facello','Peac');